name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: Build WASM Lib
        run: yarn build:wasm
      
      - name: Install Dependencies
        run: |
          yarn add ./fib-wasm-lib/pkg
          yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Build App
        run: yarn build

      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB_WORKERS_EXAMPLE }}"
          projectId: web-workers-example
